name: PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  lint:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            ci
            build
            refactor
            perf
            test
            revert
            deps
            deps-dev
          requireScope: false
          subjectPattern: ^[A-Za-z].+$
          headerPattern: '^([\w\-]*)(?:\(([\w$.\-*/ ]*)\))?: (.*)$'
          headerPatternCorrespondence: type, scope, subject
